name: Build Executables

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows-64bit
          - os: macos-13
            name: mac-intel
          - os: macos-14
            name: mac-arm
          - os: ubuntu-latest
            name: linux-64bit

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Używamy bardzo stabilnej wersji dla dobrej kompatybilności
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: pyinstaller --onefile main.py --name screenshoter-${{ matrix.name }}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: screenshoter-${{ matrix.name }}
        path: dist/*
        
    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"
        name: "Najnowsza wersja (Auto-Release)"
        files: dist/screenshoter-${{ matrix.name }}*
